apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: cert-manager-wildcard-certificate
  namespace: istio-system
spec:
  secretName: onepanel-tls
  issuerRef:
    name: cert-manager-acme-dns-issuer
    kind: ClusterIssuer
  commonName: $(commonName)
  dnsNames:
  - $(commonName)
  acme:
    config:
    - dns01:
        provider: <patch-me>
      domains:
      - $(commonName)