apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
 - application
 - onepanel
 - argo
commonLabels:
  app.kubernetes.io/name: onepanel
  app.kubernetes.io/instance: onepanel-v0.1.0
  app.kubernetes.io/managed-by: onepanel-cli
  app.kubernetes.io/component: onepanel
  app.kubernetes.io/part-of: onepanel
  app.kubernetes.io/version: v0.1.0