apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
 - application
 - cert-manager
 - istio
 - argo
 - common/onepanel/overlays/istio
 - common/cert-manager/overlays/aws
 - onepanel/base
 - storage/overlays/gcp
configurations:
 - configs/varreference.yaml
configMapGenerator:
 - name: onepanel-base-parameters
   envs:
    - ./vars/params.env
vars:
 - name: onepanelNamespace
   objref:
    kind: ConfigMap
    name: onepanel-base-parameters
    apiVersion: v1
   fieldref:
    fieldpath: data.onepanelNamespace