apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
 - application
 - cert-manager
 - istio
 - argo
 - common/onepanel/overlays/istio
 - common/cert-manager/overlays/aws
 - onepanel/base
 - storage/overlays/gcp
configurations:
 - configs/varreference.yaml
configMapGenerator:
 - name: onepanel
   namespace: onepanel
   envs:
     - ./vars/workflow-config-map.env
     - ./vars/onepanel-config-map.env
     - ./vars/logging-config-map.env
generatorOptions:
  disableNameSuffixHash: true
vars:
 - name: defaultNamespace
   objref:
    kind: ConfigMap
    name: onepanel
    apiVersion: v1
   fieldref:
    fieldpath: data.onepanelDefaultConfigMapNamespace