apiVersion: v1
kind: ConfigMap
metadata:
  name: onepanel
  namespace: onepanel
data:
  namespace: $(onepanelNamespace)
  argo:
    artifactRepository:
      archiveLogs: true
      s3:
        bucket: $(artifactRepositoryBucket)
        keyFormat: artifacts/{{workflow.namespace}}/{{workflow.name}}/{{pod.name}}
        endpoint: $(artifactRepositoryEndpoint)
        insecure: $(artifactRepositoryInsecure)
        accessKeySecret:
          name: $(artifactRepositoryAccessKeySecretName)
          key: $(artifactRepositoryAccessKeySecretKey)
        secretKeySecret:
          name: $(artifactRepositorySecretKeySecretName)
          key: $(artifactRepositorySecretKeySecretKey)
