apiVersion: v1
kind: ConfigMap
metadata:
  name: onepanel
  namespace: onepanel
data:
  onepanelApiUrl: $(onepanelApiUrl)
  providerType: $(providerType)
  databaseHost: $(databaseHost)
  databasePort: $(databasePort)
  databaseName: $(databaseDatabaseName)
  databaseDriverName: $(databaseDriverName)