apiVersion: v1
kind: ConfigMap
metadata:
  name: onepanel
  namespace: onepanel
data:
  defaultNamespace: $(defaultNamespace)
  databaseHost: $(databaseHost)
  databasePort: $(databasePort)
  databaseDatabase: $(databaseDatabase)
  databaseDriverName: $(databaseDriverName)