apiVersion: v1
kind: ConfigMap
metadata:
  name: onepanel
  namespace: onepanel
data:
  databaseHost: $(databaseHost)
  databasePort: $(databasePort)
  databaseName: $(databaseDatabaseName)
  databaseDriverName: $(databaseDriverName)