apiVersion: v1
kind: ConfigMap
metadata:
  name: onepanel
  namespace: $(applicationDefaultNamespace)
data:
  artifactRepository: |
    archiveLogs: true
    s3:
      region: $(artifactRepositoryProviderRegion)
      bucket: $(artifactRepositoryProviderBucket)
      keyFormat: $(artifactRepositoryProviderKeyFormat)
      endpoint: $(artifactRepositoryProviderEndpoint)
      insecure: $(artifactRepositoryProviderInsecure)
      accessKeySecret:
        name: $(artifactRepositoryProviderKeysAccessKeySecretName)
        key: $(artifactRepositoryProviderKeysAccessKeySecretKey)
      secretKeySecret:
        name: $(artifactRepositoryProviderKeysSecretKeySecretName)
        key: $(artifactRepositoryProviderKeysSecretKeySecretKey)