# onepanel-core-ui deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: onepanel-core-ui
  labels:
    app: onepanel-core-ui
  namespace: onepanel
spec:
  template:
    metadata:
      name: onepanel-core-ui
      labels:
        app: onepanel-core-ui
    spec:
      automountServiceAccountToken: false
      containers:
        - name: onepanel-core-ui
          image: onepanel/core-ui:0.5.7
          ports:
            - containerPort: 4200
            - containerPort: 80
  selector:
    matchLabels:
      app: onepanel-core-ui
---
# onepanel-core-ui service
apiVersion: v1
kind: Service
metadata:
  name: onepanel-core-ui
  namespace: onepanel
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      name: "http"
  selector:
    app: onepanel-core-ui