apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
 - namespace.yaml
 - network-policy.yaml
 - application.yaml
 - add-label.yaml
 - add-network-policy.yaml
 - add-role.yaml
  - secret.yaml
commonLabels:
  app.kubernetes.io/name: onepanel
  app.kubernetes.io/instance: onepanel-v0.1.0
  app.kubernetes.io/managed-by: onepanel-cli
  app.kubernetes.io/component: onepanel
  app.kubernetes.io/part-of: onepanel
  app.kubernetes.io/version: v0.1.0
configMapGenerator:
 - name: onepanel
   namespace: onepanel
   envs:
     - ../../argo/base/params.env
     - ../../../vars/params.env
generatorOptions:
  disableNameSuffixHash: true
vars:
  - name: artifactRepositoryBucket
    objref:
      kind: ConfigMap
      name: onepanel
      apiVersion: v1
    fieldref:
      fieldpath: data.artifactRepositoryBucket
  - name: artifactRepositoryEndpoint
    objref:
      kind: ConfigMap
      name: onepanel
      apiVersion: v1
    fieldref:
      fieldpath: data.artifactRepositoryEndpoint
  - name: artifactRepositoryInsecure
    objref:
      kind: ConfigMap
      name: onepanel
      apiVersion: v1
    fieldref:
      fieldpath: data.artifactRepositoryInsecure
  - name: artifactRepositoryAccessKeySecretName
    objref:
      kind: ConfigMap
      name: onepanel
      apiVersion: v1
    fieldref:
      fieldpath: data.artifactRepositoryAccessKeySecretName
  - name: artifactRepositoryAccessKeySecretKey
    objref:
      kind: ConfigMap
      name: onepanel
      apiVersion: v1
    fieldref:
      fieldpath: data.artifactRepositoryAccessKeySecretKey
  - name: artifactRepositorySecretKeySecretName
    objref:
      kind: ConfigMap
      name: onepanel
      apiVersion: v1
    fieldref:
      fieldpath: data.artifactRepositorySecretKeySecretName
  - name: artifactRepositorySecretKeySecretKey
    objref:
      kind: ConfigMap
      name: onepanel
      apiVersion: v1
    fieldref:
      fieldpath: data.artifactRepositorySecretKeySecretKey