apiVersion: v1
kind: Secret
metadata:
  name: onepanel
  namespace: $(onepanelNamespace)
type: Opaque
stringData:
  argoArtifactRepositoryS3Bucket: $(artifactRepositoryBucket)
  argoArtifactRepositoryS3KeyFormat: artifacts/{{workflow.namespace}}/{{workflow.name}}/{{pod.name}}
  argoArtifactRepositoryS3Endpoint: $(artifactRepositoryEndpoint)
  argoArtifactRepositoryS3Insecure: $(artifactRepositoryInsecure)
  argoArtifactRepositoryS3AccessKeySecretName: $(artifactRepositoryAccessKeySecretName)
  argoArtifactRepositoryS3AccessKeySecretKey: $(artifactRepositoryAccessKeySecretKey)
  argoArtifactRepositoryS3SecretKeySecretName: $(artifactRepositorySecretKeySecretName)
  argoArtifactRepositoryS3SecretKeySecretKey: $(artifactRepositorySecretKeySecretKey)