# onepanel-core-ui service
apiVersion: v1
kind: Service
metadata:
  name: onepanel-core-ui
  namespace: onepanel
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      name: "http"
  selector:
    app: onepanel-core-ui