apiVersion: v1
kind: Secret
metadata:
  name: modeldb-secret
  namespace: $(applicationDefaultNamespace)
type: Opaque
# These values will be replaced by the CLI, not Kustomize
stringData:
  databaseName: $(componentsModelDbDatabaseDatabaseName)
  databaseHost: $(componentsModelDbDatabaseHost)
  databasePort: $(componentsModelDbDatabasePort)
  databaseUsername: $(componentsModelDbDatabaseUsername)
  databasePassword: $(componentsModelDbDatabasePassword)



