apiVersion: v1
kind: Secret
metadata:
  name: modeldb-secret
  namespace: $(applicationDefaultNamespace)
type: Opaque
# These values will be replaced by the CLI, not Kustomize
stringData:
  databaseName: $(servicesModelDbDatabaseDatabaseName)
  databaseHost: $(servicesModelDbDatabaseHost)
  databasePort: $(servicesModelDbDatabasePort)
  databaseUsername: $(servicesModelDbDatabaseUsername)
  databasePassword: $(servicesModelDbDatabasePassword)



