apiVersion: v1
kind: Service
metadata:
  name: modeldb-backend
  namespace: onepanel
  labels:
    app: modeldb
    component: backend
spec:
  ports:
    - name: backend
      port: 8085
    - name: artifactstore
      port: 8086
    - name: http
      port: 3005
      targetPort: 3000
  selector:
    app: modeldb
    component: backend
  type: ClusterIP