apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
 - cert-manager.yaml
 - certificate.yaml
 - cluster-issuer.yaml
transformers:
- metadataLabelTransformer.yaml
configMapGenerator:
 - name: cert-manager-config
   envs:
    - ../../vars/params.env
secretGenerator:
 - name: cert-manager-secret
   namespace: onepanel
   envs:
    - ../../vars/params.env
vars:
 - name: email
   objref:
    kind: ConfigMap
    name: cert-manager-config
    apiVersion: v1
   fieldref:
    fieldpath: data.CERT-MANAGER_EMAIL
 - name: commonName
   objref:
    kind: ConfigMap
    name: cert-manager-config
    apiVersion: v1
   fieldref:
    fieldpath: data.CERT-MANAGER_COMMON_NAME