apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: core-ui
  namespace: onepanel
spec:
  hosts:
    - $(applicationHost)
  gateways:
    - istio-system/ingressgateway
  http:
    - match:
        - uri:
            prefix: $(applicationUiPath)
      route:
        - destination:
            port:
              number: 80
            host: onepanel-core-ui