apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: cert-manager-acme-dns-issuer
spec:
  acme:
    solvers:
    - selector: {}
      dns01:
        route53:
          region: $(aws_region)
          accessKeyID: $(aws_access_key)
          secretAccessKeySecretRef:
            key: AWS_SECRET_KEY
            name: cert-manager