apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: onepanel
provisioner: kubernetes.io/aws-ebs
parameters:
  type: io1
  iopsPerGB: "10"
  fsType: ext4
reclaimPolicy: Delete
volumeBindingMode: Immediate