apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: instance-creator-
spec:
  entrypoint: instance-tmpl
  arguments:
    parameters:
    - name: instance-name
      value: instance-name
    - name: instance-namespace
      value: instance-namespace
    - name: action
      value: create
  templates:
  - name: instance-tmpl
    steps:
    - - name: create-instance-service
        templateRef:
          name: instance-service-tmpl
          template: instance-service-tmpl
    - - name: create-instance-virtual-service
        templateRef:
          name: instance-virtual-service-tmpl
          template: instance-virtual-service-tmpl
    - - name: create-instance-statefulset
        templateRef:
          name: instance-statefulset-tmpl
          template: instance-statefulset-tmpl
