apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: onepanel
provisioner: kubernetes.io/azure-disk
parameters:
  storageaccounttype: Premium_LRS
  kind: Dedicated
reclaimPolicy: Delete
volumeBindingMode: Immediate