apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: cert-manager-acme-dns-issuer
spec:
  acme:
    # You must replace this email address with your own.
    # Let's Encrypt will use this to contact you about expiring
    # certificates, and issues related to your account.
    email: admin@onepanel.io
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource used to store the account's private key.
      name: cert-manager-acme-dns-issuer--private-key
    # Enable the DNS01 challenge mechanism for this Issuer
    dns01:
      providers:
      - name: aws
        route53:
          region: us-west-2
          accessKeyID: <aws-access-key>
          secretAccessKeySecretRef:
            name: onepanel-env
            key: AWS_SECRET_KEY