apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: onepanel
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: onepanel
      app.kubernetes.io/instance: onepanel-v0.1.0
      app.kubernetes.io/managed-by: onepanel
      app.kubernetes.io/component: onepanel
      app.kubernetes.io/part-of: onepanel
      app.kubernetes.io/version: v0.1.0
  componentKinds:
  - group: core
    kind: Namespace
  descriptor:
    type: argo
    version: v1beta1
    description: Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes
    maintainers: []
    owners: []
    keywords:
     - argo
     - onepanel
    links:
    - description: About
      url: https://github.com/argoproj/argo
  addOwnerRef: true

