apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
  namespace: onepanel
data:
  config: |
    executorImage: $(executorImage)
    containerRuntimeExecutor: $(containerRuntimeExecutor)
    artifactRepository:
      archiveLogs: true
      s3:
        bucket: $(artifactRepositoryBucket)
        keyFormat: $(artifactRepositoryKeyFormat)
        endpoint: $(artifactRepositoryEndpoint)
        insecure: $(artifactRepositoryInsecure)
        accessKeySecret:
          name: $(artifactRepositoryAccessKeySecretName)
          key: $(artifactRepositoryAccessKeySecretKey)
        secretKeySecret: 
          name: $(artifactRepositorySecretKeySecretName)
          key: $(artifactRepositorySecretKeySecretKey)