apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cluster-role-binding.yaml
- cluster-role.yaml
- config-map.yaml
- crd.yaml
- deployment.yaml
- service-account.yaml
- service.yaml
commonLabels:
  app.kubernetes.io/name: argo
  app.kubernetes.io/instance: argo-v2.4.2
  app.kubernetes.io/managed-by: onepanel-cli
  app.kubernetes.io/component: argo
  app.kubernetes.io/part-of: onepanel
  app.kubernetes.io/version: v2.4.2
images:
- name: argoproj/argoui
  newName: argoproj/argoui
  newTag: v2.4.2
- name: argoproj/workflow-controller
  newName: argoproj/workflow-controller
  newTag: v2.4.2
configMapGenerator:
- name: workflow-controller-parameters
  envs:
   - params.env
   - ../../../vars/params.env
generatorOptions:
  disableNameSuffixHash: true
vars:
- name: executorImage
  objref:
    kind: ConfigMap
    name: workflow-controller-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.executorImage
- name: containerRuntimeExecutor
  objref:
    kind: ConfigMap
    name: workflow-controller-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.containerRuntimeExecutor
- name: artifactRepositoryBucket
  objref:
    kind: ConfigMap
    name: workflow-controller-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.artifactRepositoryBucket
- name: artifactRepositoryKeyPrefix
  objref:
    kind: ConfigMap
    name: workflow-controller-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.artifactRepositoryKeyPrefix
- name: artifactRepositoryEndpoint
  objref:
    kind: ConfigMap
    name: workflow-controller-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.ARTIFACT_REPOSITORY_ENDPOINT
- name: artifactRepositoryInsecure
  objref:
    kind: ConfigMap
    name: workflow-controller-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.artifactRepositoryInsecure
- name: artifactRepositoryAccessKeySecretName
  objref:
    kind: ConfigMap
    name: workflow-controller-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.ARTIFACT_REPOSITORY_ACCESS_KEY_SECRET_NAME
- name: artifactRepositoryAccessKeySecretKey
  objref:
    kind: ConfigMap
    name: workflow-controller-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.ARTIFACT_REPOSITORY_ACCESS_KEY_SECRET_KEY
- name: artifactRepositorySecretKeySecretName
  objref:
    kind: ConfigMap
    name: workflow-controller-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.ARTIFACT_REPOSITORY_SECRET_KEY_SECRET_NAME
- name: artifactRepositorySecretKeySecretKey
  objref:
    kind: ConfigMap
    name: workflow-controller-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.ARTIFACT_REPOSITORY_SECRET_KEY_SECRET_KEY
configurations:
- params.yaml
