# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Component: Artifact repository
# Description: S3 compatible object storage for storing files across Onepanel
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
artifactRepository:
  s3:
    # S3 access key
    accessKey:
      required: true
      default: <access-key>
    # S3 secret key
    secretKey:
      required: true
      default: <secret-key>
    # Name of bucket, example: my-bucket
    bucket:
      required: true
      default: <bucket-name>
    # Endpoint for S3 compatible storage
    # Supported provider endpoints:
    #   AWS: s3.amazonaws.com
    #   GCS: storage.googleapis.com
    #   Minio: my-minio-endpoint.default:9000
    endpoint:
      required: true
      default: s3.amazonaws.com
    # Change to true if endpoint does NOT support HTTPS
    insecure:
      required: true
      default: false
    # Bucket region
    region:
      required: true
      default: us-west-2
    # Key Format for objects stored by Workflows. This can reference Workflow variables
    keyFormat:
      required: true
      default: artifacts/{{workflow.namespace}}/{{workflow.name}}/{{pod.name}}
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Component: workflow engine configuration
# Description: Various options to adjust workflow engine behavior
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
workflowEngine:
  # Specifies the container runtime interface to use (default: docker)
  # must be one of: docker, kubelet, k8sapi, pns
  # Ref: https://github.com/argoproj/argo/blob/master/docs/workflow-controller-configmap.yaml
  containerRuntimeExecutor:
    required: true
    default: docker