artifact_repository:
  endpoint:
    required: true
    default: minio-service.onepanel:9000
  bucket:
    require: true
    default: mlpipeline.onepanel.io
  access_key:
    required: true
    default: fillmeout
  secret_key:
    required: true
    default: fillmeout