workflow:
  artifactRepository:
    secrets:
      accessKey:
        required: true
        default: fillmeout
      secretKey:
        required: true
        default: fillmeout
    configMap:
      endpoint:
        required: true
        default: minio-service.onepanel:9000
      bucket:
        require: true
        default: mlpipeline.onepanel.io