artifactRepository:
  accessKey:
    required: true
    default: fillmeout
  secretKey:
    required: true
    default: fillmeout
  bucket:
    required: true
    default: mlpipeline.onepanel.io
  endpoint:
    required: true
    default: minio-service.onepanel:9000
  insecure:
    required: true
    default: false
  region:
    required: true
    default: us-west-2