artifactRepository:
  accessKey:
    required: true
    default: <access-key>
  secretKey:
    required: true
    default: <secret-key>
  bucket:
    required: true
    default: <bucket-name>
  endpoint:
    required: true
    default: s3.amazonaws.com
  insecure:
    required: true
    default: false
  region:
    required: true
    default: us-west-2