artifactRepository:
  endpoint:
    required: true
    default: minio-service.onepanel:9000
  bucket:
    require: true
    default: mlpipeline.onepanel.io
  accessKey:
    required: true
    default: fillmeout
  secretKey:
    required: true
    default: fillmeout
  keyFormat:
    required: true
    default: {{workflow.namespace}}/{{workflow.name}}/{{pod.name}}