apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: cert-manager-wildcard-certificate
  namespace: istio-system
spec:
  acme:
    config:
    - dns01:
        provider: aws
      domains:
      - $(commonName)