apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
 - cert-manager.yaml
commonLabels:
  app.kubernetes.io/name: cert-manager
  app.kubernetes.io/instance: cert-manager-v0.11.0
  app.kubernetes.io/managed-by: onepanel-cli
  app.kubernetes.io/component: cert-manager
  app.kubernetes.io/part-of: onepanel
  app.kubernetes.io/version: v0.11.0
