apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
 - certificate.yaml
 - cluster-issuer.yaml
commonLabels:
  app.kubernetes.io/name: cert-manager
  app.kubernetes.io/instance: cert-manager-v0.11.0
  app.kubernetes.io/managed-by: onepanel-cli
  app.kubernetes.io/component: cert-manager
  app.kubernetes.io/part-of: onepanel
  app.kubernetes.io/version: v0.11.0
configMapGenerator:
 - name: cert-manager-config
   env: ../../../vars/params.env
vars:
 - name: email
   objref:
    kind: ConfigMap
    name: cert-manager-config
    apiVersion: v1
   fieldref:
    fieldpath: data.email
 - name: cert-manager-config
   objref:
    kind: ConfigMap
    name: custom-vars-2
    apiVersion: v1
   fieldref:
    fieldpath: data.commonName