apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kube-logging.yaml
  - elasticsearch_svc.yaml
  - elasticsearch_statefulset.yaml
  - kibana.yaml
  - fluentd.yaml
commonLabels:
  app.kubernetes.io/managed-by: onepanel-cli
  app.kubernetes.io/part-of: onepanel
configMapGenerator:
  - name: logging-config
    envs:
      - ../../vars/logging-config-map.env
vars:
  - name: loggingElasticSearchImage
    objref:
      kind: ConfigMap
      name: logging-config
      apiVersion: v1
    fieldref:
      fieldpath: data.loggingImage
  - name:  loggingVolumeStorage
    objref:
      kind: ConfigMap
      name: logging-config
      apiVersion: v1
    fieldref:
      fieldpath: data.loggingVolumeStorage